version: '3'
services:
  gitea:
    image: gitea/gitea:1.20
    container_name: gitea
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app.ini:/data/gitea/conf/app.ini:Z
    environment:
      - USER_UID=1000
      - USER_GID=1000